/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Juanjo
 */
public class Ventana extends javax.swing.JFrame {

    public float primerNumero;
    public float segundoNumero;
    public String operador;
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        lbPantalla = new javax.swing.JLabel();
        tfPantalla = new javax.swing.JTextField();
        btIgual = new javax.swing.JLabel();
        bt2 = new javax.swing.JLabel();
        btDividir = new javax.swing.JLabel();
        bt4 = new javax.swing.JLabel();
        bt5 = new javax.swing.JLabel();
        bt6 = new javax.swing.JLabel();
        bt7 = new javax.swing.JLabel();
        bt8 = new javax.swing.JLabel();
        bt9 = new javax.swing.JLabel();
        bt0 = new javax.swing.JLabel();
        btMultiplicar = new javax.swing.JLabel();
        btMenos = new javax.swing.JLabel();
        btMas = new javax.swing.JLabel();
        bt3 = new javax.swing.JLabel();
        bt1 = new javax.swing.JLabel();
        btClean = new javax.swing.JLabel();
        btBorrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(450, 450));

        panelFondo.setBackground(new java.awt.Color(102, 102, 102));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbPantalla.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        lbPantalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panelFondo.add(lbPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 350, 30));

        tfPantalla.setFont(new java.awt.Font("Roboto Slab", 0, 24)); // NOI18N
        panelFondo.add(tfPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 370, 70));

        btIgual.setBackground(new java.awt.Color(51, 51, 51));
        btIgual.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btIgual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btIgual.setText("=");
        btIgual.setOpaque(true);
        btIgual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btIgualMouseClicked(evt);
            }
        });
        panelFondo.add(btIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 40, 40));

        bt2.setBackground(new java.awt.Color(51, 51, 51));
        bt2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        bt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt2.setText("2");
        bt2.setOpaque(true);
        bt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt2MouseClicked(evt);
            }
        });
        panelFondo.add(bt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 40, 40));

        btDividir.setBackground(new java.awt.Color(51, 51, 51));
        btDividir.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btDividir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btDividir.setText("/");
        btDividir.setOpaque(true);
        btDividir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDividirMouseClicked(evt);
            }
        });
        panelFondo.add(btDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 40, 40));

        bt4.setBackground(new java.awt.Color(51, 51, 51));
        bt4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        bt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt4.setText("4");
        bt4.setOpaque(true);
        bt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt4MouseClicked(evt);
            }
        });
        panelFondo.add(bt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 40, 40));

        bt5.setBackground(new java.awt.Color(51, 51, 51));
        bt5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        bt5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt5.setText("5");
        bt5.setOpaque(true);
        bt5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt5MouseClicked(evt);
            }
        });
        panelFondo.add(bt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 40, 40));

        bt6.setBackground(new java.awt.Color(51, 51, 51));
        bt6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        bt6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt6.setText("6");
        bt6.setOpaque(true);
        bt6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt6MouseClicked(evt);
            }
        });
        panelFondo.add(bt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 40, 40));

        bt7.setBackground(new java.awt.Color(51, 51, 51));
        bt7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        bt7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt7.setText("7");
        bt7.setOpaque(true);
        bt7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt7MouseClicked(evt);
            }
        });
        panelFondo.add(bt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 40, 40));

        bt8.setBackground(new java.awt.Color(51, 51, 51));
        bt8.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        bt8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt8.setText("8");
        bt8.setOpaque(true);
        bt8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt8MouseClicked(evt);
            }
        });
        panelFondo.add(bt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 40, 40));

        bt9.setBackground(new java.awt.Color(51, 51, 51));
        bt9.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        bt9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt9.setText("9");
        bt9.setOpaque(true);
        bt9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt9MouseClicked(evt);
            }
        });
        panelFondo.add(bt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 40, 40));

        bt0.setBackground(new java.awt.Color(51, 51, 51));
        bt0.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        bt0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt0.setText("0");
        bt0.setOpaque(true);
        bt0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt0MouseClicked(evt);
            }
        });
        panelFondo.add(bt0, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 40, 40));

        btMultiplicar.setBackground(new java.awt.Color(51, 51, 51));
        btMultiplicar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btMultiplicar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btMultiplicar.setText("*");
        btMultiplicar.setOpaque(true);
        btMultiplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btMultiplicarMouseClicked(evt);
            }
        });
        panelFondo.add(btMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 40, 40));

        btMenos.setBackground(new java.awt.Color(51, 51, 51));
        btMenos.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btMenos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btMenos.setText("-");
        btMenos.setOpaque(true);
        btMenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btMenosMouseClicked(evt);
            }
        });
        panelFondo.add(btMenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 40, 40));

        btMas.setBackground(new java.awt.Color(51, 51, 51));
        btMas.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btMas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btMas.setText("+");
        btMas.setOpaque(true);
        btMas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btMasMouseClicked(evt);
            }
        });
        panelFondo.add(btMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 40, 40));

        bt3.setBackground(new java.awt.Color(51, 51, 51));
        bt3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        bt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt3.setText("3");
        bt3.setOpaque(true);
        bt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt3MouseClicked(evt);
            }
        });
        panelFondo.add(bt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 40, 40));

        bt1.setBackground(new java.awt.Color(51, 51, 51));
        bt1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        bt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt1.setText("1");
        bt1.setOpaque(true);
        bt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt1MouseClicked(evt);
            }
        });
        panelFondo.add(bt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 40, 40));

        btClean.setBackground(new java.awt.Color(51, 51, 51));
        btClean.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btClean.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btClean.setText("C");
        btClean.setOpaque(true);
        btClean.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCleanMouseClicked(evt);
            }
        });
        panelFondo.add(btClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 40, 40));

        btBorrar.setBackground(new java.awt.Color(51, 51, 51));
        btBorrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btBorrar.setText("Borrar unidad");
        btBorrar.setOpaque(true);
        btBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btBorrarMouseClicked(evt);
            }
        });
        panelFondo.add(btBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Botón diseñado para mostrar el total de toda la operación
     * @param evt click del botón con el simbolo igual (10)
     */
    private void btIgualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIgualMouseClicked
        //TODO: hacer que solo se muestre en la casilla donde se escribe 
        // el numero con el resultado.
        this.segundoNumero = Float.parseFloat(lbPantalla.getText());
        switch(this.operador){
            case "+":
                this.lbPantalla.setText(Float.toString(this.primerNumero+this.segundoNumero));
                break;
            case "-":
                this.lbPantalla.setText(Float.toString(primerNumero-this.segundoNumero));
                break;
            case "*":
                this.lbPantalla.setText(Float.toString(primerNumero*this.segundoNumero));
                break;
            case "/":
                this.lbPantalla.setText(Float.toString(primerNumero/this.segundoNumero));
                break;
        }
    }//GEN-LAST:event_btIgualMouseClicked

    /**
     * Método para seleccionar el número 2
     * @param evt click al botón con el número dos (2)
     */
    private void bt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt2MouseClicked
        lbPantalla.setText(this.lbPantalla.getText() + "2");
    }//GEN-LAST:event_bt2MouseClicked

    /**
     * Método para seleccionar el número 3
     * @param evt click al botón con el número 3
     */
    private void bt3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt3MouseClicked
        lbPantalla.setText(this.lbPantalla.getText() + "3");
    }//GEN-LAST:event_bt3MouseClicked

    /**
     * Método para seleccionar el número 4
     * @param evt click al botón con el número 4
     */
    private void bt4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt4MouseClicked
        lbPantalla.setText(this.lbPantalla.getText() + "4");
    }//GEN-LAST:event_bt4MouseClicked

    /**
     * Método para seleccionar el número 5
     * @param evt click al botón con el número 5
     */
    private void bt5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt5MouseClicked
        lbPantalla.setText(this.lbPantalla.getText() + "5");
    }//GEN-LAST:event_bt5MouseClicked

    /**
     * Método para seleccionar el número 6
     * @param evt click al botón con el número 6
     */
    private void bt6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt6MouseClicked
        lbPantalla.setText(this.lbPantalla.getText() + "6");
    }//GEN-LAST:event_bt6MouseClicked

    /**
     * Método para seleccionar el número 7
     * @param evt click al botón con el número 7
     */
    private void bt7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt7MouseClicked
        lbPantalla.setText(this.lbPantalla.getText() + "7");
    }//GEN-LAST:event_bt7MouseClicked

    /**
     * Método para seleccionar el número 8
     * @param evt click al botón con el número 8
     */
    private void bt8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt8MouseClicked
        lbPantalla.setText(this.lbPantalla.getText() + "8");
    }//GEN-LAST:event_bt8MouseClicked

    /**
     * Método para seleccionar el número 9
     * @param evt click al botón con el número 9
     */
    private void bt9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt9MouseClicked
        lbPantalla.setText(this.lbPantalla.getText() + "9");
    }//GEN-LAST:event_bt9MouseClicked

    private void bt0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt0MouseClicked
        lbPantalla.setText(this.lbPantalla.getText() + "0");
    }//GEN-LAST:event_bt0MouseClicked

    /**
     * Método para realizar la suma entre valores
     * @param evt click al botón con el simbolo más (+)
     */
    private void btMasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMasMouseClicked
        //Almacenamos el primer número en una variable
        this.primerNumero = Float.parseFloat(lbPantalla.getText());
        this.operador = "+"; //Asignamos el valor del operador a suma
        lbPantalla.setText(""); //Dejamos el campo vacío    
    }//GEN-LAST:event_btMasMouseClicked

    /**
     * Método para realizar la resta entre valores
     * @param evt click al botón con el simbolo (-)
     */
    private void btMenosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMenosMouseClicked
        //Almacenamos el primer número en una variable
        this.primerNumero = Float.parseFloat(lbPantalla.getText());
        this.operador = "-"; //Asignamos el valor del operador a resta
        lbPantalla.setText(""); //Dejamos el campo vacío
    }//GEN-LAST:event_btMenosMouseClicked

    /**
     * Método para realizar la multiplicación entre valores
     * @param evt click al botón con el simbolo *
     */
    private void btMultiplicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMultiplicarMouseClicked
        //Almacenamos el primer número en una variable
        this.primerNumero = Float.parseFloat(lbPantalla.getText());
        this.operador = "*"; //Asignamos el valor del operador a multiplicación
        lbPantalla.setText(""); //Dejamos el campo vacío
    }//GEN-LAST:event_btMultiplicarMouseClicked

    /**
     * Método para realizar la división entre valores
     * @param evt click al botón con el simbolo /
     */
    private void btDividirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDividirMouseClicked
        //Almacenamos el primer número en una variable
        this.primerNumero = Float.parseFloat(lbPantalla.getText());
        this.operador = "/";//Asignamos el valor del operador a división
        lbPantalla.setText(""); //Dejamos el campo vacío
    }//GEN-LAST:event_btDividirMouseClicked

    /**
     * Método para seleccionar el número 1
     * @param evt click en el número 1
     */
    private void bt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt1MouseClicked
        lbPantalla.setText(this.lbPantalla.getText() + "1");
    }//GEN-LAST:event_bt1MouseClicked

    /**
     * Este método sirve para borrar el texto que esté en la barra para escribir
     * los valores de la calculadora
     * @param evt Click al botón con la letra c
     */
    private void btCleanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCleanMouseClicked
        lbPantalla.setText("");
    }//GEN-LAST:event_btCleanMouseClicked

    /**
     * Método para borrar un valor de la pantalla de operaciones
     * @param evt click al botón de Borrar unidad.
     */
    private void btBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBorrarMouseClicked
        String texto = lbPantalla.getText();
        texto = texto.substring(0, texto.length()-1);
        lbPantalla.setText(texto);
    }//GEN-LAST:event_btBorrarMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bt0;
    private javax.swing.JLabel bt1;
    private javax.swing.JLabel bt2;
    private javax.swing.JLabel bt3;
    private javax.swing.JLabel bt4;
    private javax.swing.JLabel bt5;
    private javax.swing.JLabel bt6;
    private javax.swing.JLabel bt7;
    private javax.swing.JLabel bt8;
    private javax.swing.JLabel bt9;
    private javax.swing.JLabel btBorrar;
    private javax.swing.JLabel btClean;
    private javax.swing.JLabel btDividir;
    private javax.swing.JLabel btIgual;
    private javax.swing.JLabel btMas;
    private javax.swing.JLabel btMenos;
    private javax.swing.JLabel btMultiplicar;
    private javax.swing.JLabel lbPantalla;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JTextField tfPantalla;
    // End of variables declaration//GEN-END:variables
}
